import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from 'next/script'
import GlobalLoadingWrapper from "../../components/icomat1/GlobalLoadingWrapper";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  generator: "WordPress 6.7.2",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="https://api.w.org/" href="/wp-json/" />
      </head>
      <body>
        <Script 
          src="https://cdn.jsdelivr.net/npm/three-bas@2.0.1/dist/bas.min.js"
          strategy="lazyOnload"
        />
        <GlobalLoadingWrapper>{children}</GlobalLoadingWrapper>
      </body>
    </html>
  )
}
