"use client";

import {
  SiWordpress,
  SiDrupal,
  SiCraftcms,
  SiContentful,
  SiWebflow,
  SiWix,
  SiSquarespace,
  SiHtml5,
  SiCss,
  SiJavascript,
  SiTypescript,
  SiReact,
  SiNextdotjs,
  SiAstro,
  SiVuedotjs,
  SiSvelte,
  SiTailwindcss,
  SiBootstrap,
  SiSass,
  SiPhp,
  SiNodedotjs,
  SiPython,
  SiPagespeedinsights,
  SiVercel,
  SiNetlify,
  SiCloudflare,
  SiCpanel,
  SiWoocommerce,
  SiShopify,
  SiLaravel,
  SiDjango,
  SiDigitalocean,
  SiGit,
  SiGithub,
  SiGitlab,
  SiLetsencrypt,
  SiExpress,
  SiNestjs,
  SiPostgresql,
  SiMysql,
  SiMongodb,
  SiFirebase,
  SiAuth0,
  SiJsonwebtokens,
  SiGraphql,
  SiDocker,
  SiPostman,
  SiStrapi,
  SiSanity,
  SiFlutter,
  SiDart,
  SiMapbox,
  SiGooglemaps,
  SiGoogleanalytics,
  SiDhl,
  SiFedex,
  SiUps,
  SiElementor,
  SiRedis,
  SiMariadb,
  SiNewrelic,
  SiGithubactions,
  SiComposer,
  SiWeb3Dotjs,
} from "react-icons/si";
import {
  FaAws,
  FaMicrosoft,
  FaShieldAlt,
  FaKey,
  FaUserLock,
  FaUsersCog,
  FaApple,
  FaFingerprint,
  FaBell,
  FaTruck,
  FaLock,
  FaServer,
  FaDatabase,
  FaTerminal,
  FaCogs,
} from "react-icons/fa";
import {
  TbCode,
  TbSeo,
  TbSchema,
  TbPhoto,
  TbLoader,
  TbNetwork,
  TbBrandOpenSource,
  TbServer,
  TbShieldLock,
  TbBug,
  TbDatabase,
  TbRocket,
  TbSpeedboat,
  TbShoppingCart,
  TbCreditCard,
  TbApi,
  TbWebhook,
  TbFileDescription,
  TbTestPipe,
  TbAccessible,
  TbPuzzle,
  TbBrandReactNative,
  TbCurrentLocation,
  TbDeviceMobile,
  TbPackage,
  TbBlocks,
  TbLayout,
  TbBrandPhp,
  TbCloudLock,
  TbBrandSpeedtest,
} from "react-icons/tb";

const SIZE = 22;

function PaymentBrandLogo({ file, name }) {
  return (
    <img
      src={`/payment-icons/${file}`}
      alt=""
      title={name}
      width="26"
      height="22"
      loading="lazy"
      decoding="async"
      style={{
        display: "block",
        width: 26,
        height: 22,
        objectFit: "contain",
        borderRadius: 3,
      }}
    />
  );
}

function ErpBrandLogo({ file, name }) {
  return (
    <img
      src={`/erp-icons/${file}`}
      alt=""
      title={name}
      width="26"
      height="22"
      loading="lazy"
      decoding="async"
      style={{
        display: "block",
        width: 26,
        height: 22,
        objectFit: "contain",
        borderRadius: 3,
      }}
    />
  );
}

/**
 * Brand / concept icons for tech stack tiles.
 */
export default function TechBrandIcon({ name, color = "#c8f04a" }) {
  const props = { size: SIZE, color, "aria-hidden": true };
  const key = name.toLowerCase();

  const map = {
    wordpress: <SiWordpress {...props} />,
    "wordpress multisite": <SiWordpress {...props} />,
    "gutenberg / block editor": <TbBlocks {...props} />,
    "wp-cli": <FaTerminal {...props} />,
    bedrock: <TbBrandPhp {...props} />,
    "roots sage": <SiWordpress {...props} />,
    "advanced custom fields (acf)": <TbPuzzle {...props} />,
    "custom post types & taxonomies": <TbSchema {...props} />,
    "custom php themes": <SiPhp {...props} />,
    "block theme / fse": <TbLayout {...props} />,
    elementor: <SiElementor {...props} />,
    divi: <TbLayout {...props} />,
    "gutenberg custom blocks": <TbBlocks {...props} />,
    "timber / twig": <TbCode {...props} />,
    "generatepress / kadence": <SiWordpress {...props} />,
    "woocommerce hpos": <SiWoocommerce {...props} />,
    "woocommerce subscriptions": <SiWoocommerce {...props} />,
    "apple pay / google pay": <FaApple {...props} />,
    "html5 / css3": <SiHtml5 {...props} />,
    "javascript / typescript": <SiTypescript {...props} />,
    "faust.js": <SiWordpress {...props} />,
    "sass / scss": <SiSass {...props} />,
    "php 8.x": <SiPhp {...props} />,
    composer: <SiComposer {...props} />,
    "wordpress rest api": <TbApi {...props} />,
    wpgraphql: <SiGraphql {...props} />,
    mariadb: <SiMariadb {...props} />,
    "redis object cache": <SiRedis {...props} />,
    memcached: <FaDatabase {...props} />,
    "query monitor": <TbBrandSpeedtest {...props} />,
    "wp engine": <SiWordpress {...props} />,
    kinsta: <SiWordpress {...props} />,
    cloudways: <FaServer {...props} />,
    "litespeed / openlitespeed": <TbSpeedboat {...props} />,
    "runcloud / gridpane": <FaCogs {...props} />,
    "wp rocket": <TbRocket {...props} />,
    "litespeed cache": <TbSpeedboat {...props} />,
    "cloudflare apo": <SiCloudflare {...props} />,
    "yoast seo": <TbSeo {...props} />,
    "rank math": <TbSeo {...props} />,
    "new relic / apm": <SiNewrelic {...props} />,
    wordfence: <FaShieldAlt {...props} />,
    sucuri: <TbCloudLock {...props} />,
    "cloudflare waf": <SiCloudflare {...props} />,
    "ssl / tls": <SiLetsencrypt {...props} />,
    "2fa / least privilege": <FaUserLock {...props} />,
    "fail2ban / ssh hardening": <FaLock {...props} />,
    "local wp / laravel valet": <SiWordpress {...props} />,
    "git / github": <SiGithub {...props} />,
    "github actions": <SiGithubactions {...props} />,
    "deployhq / buddy": <TbRocket {...props} />,
    "phpunit / playwright": <TbTestPipe {...props} />,
    drupal: <SiDrupal {...props} />,
    "craft cms": <SiCraftcms {...props} />,
    "adobe experience manager (aem)": <ErpBrandLogo file="aem.svg" name="Adobe Experience Manager" />,
    contentful: <SiContentful {...props} />,
    webflow: <SiWebflow {...props} />,
    wix: <SiWix {...props} />,
    squarespace: <SiSquarespace {...props} />,
    woocommerce: <SiWoocommerce {...props} />,
    shopify: <SiShopify {...props} />,
    magento: <TbShoppingCart {...props} />,
    opencart: <TbBrandOpenSource {...props} />,
    html5: <SiHtml5 {...props} />,
    css3: <SiCss {...props} />,
    javascript: <SiJavascript {...props} />,
    typescript: <SiTypescript {...props} />,
    react: <SiReact {...props} />,
    "next.js": <SiNextdotjs {...props} />,
    astro: <SiAstro {...props} />,
    "vue.js": <SiVuedotjs {...props} />,
    svelte: <SiSvelte {...props} />,
    "tailwind css": <SiTailwindcss {...props} />,
    bootstrap: <SiBootstrap {...props} />,
    sass: <SiSass {...props} />,
    php: <SiPhp {...props} />,
    laravel: <SiLaravel {...props} />,
    "node.js": <SiNodedotjs {...props} />,
    python: <SiPython {...props} />,
    django: <SiDjango {...props} />,
    "core web vitals": <SiPagespeedinsights {...props} />,
    "google lighthouse": <TbSpeedboat {...props} />,
    "pagespeed insights": <SiPagespeedinsights {...props} />,
    gtmetrix: <TbRocket {...props} />,
    "cloudflare cdn": <SiCloudflare {...props} />,
    "technical seo": <TbSeo {...props} />,
    "schema markup": <TbSchema {...props} />,
    "image optimization": <TbPhoto {...props} />,
    "lazy loading": <TbLoader {...props} />,
    "cdn integration": <TbNetwork {...props} />,
    vercel: <SiVercel {...props} />,
    netlify: <SiNetlify {...props} />,
    cloudflare: <SiCloudflare {...props} />,
    cpanel: <SiCpanel {...props} />,
    plesk: <TbServer {...props} />,
    aws: <FaAws {...props} />,
    azure: <FaMicrosoft {...props} />,
    digitalocean: <SiDigitalocean {...props} />,
    git: <SiGit {...props} />,
    github: <SiGithub {...props} />,
    gitlab: <SiGitlab {...props} />,
    "ci/cd pipelines": <TbRocket {...props} />,
    "ssl certificates": <SiLetsencrypt {...props} />,
    "web application firewalls (waf)": <FaShieldAlt {...props} />,
    "malware scanning": <TbBug {...props} />,
    "security hardening": <TbShieldLock {...props} />,
    "automated backups": <TbDatabase {...props} />,
    "express.js": <SiExpress {...props} />,
    nestjs: <SiNestjs {...props} />,
    postgresql: <SiPostgresql {...props} />,
    mysql: <SiMysql {...props} />,
    mongodb: <SiMongodb {...props} />,
    "microsoft sql server": <FaMicrosoft {...props} />,
    firebase: <SiFirebase {...props} />,
    oauth: <SiAuth0 {...props} />,
    jwt: <SiJsonwebtokens {...props} />,
    "single sign-on (sso)": <FaKey {...props} />,
    "multi-factor authentication (mfa)": <FaUserLock {...props} />,
    "role-based access control (rbac)": <FaUsersCog {...props} />,
    stripe: <PaymentBrandLogo file="stripe.png" name="Stripe" />,
    paypal: <PaymentBrandLogo file="paypal.png" name="PayPal" />,
    paddle: <PaymentBrandLogo file="paddle.png" name="Paddle" />,
    "lemon squeezy": <PaymentBrandLogo file="lemonsqueezy.png" name="Lemon Squeezy" />,
    web3: <SiWeb3Dotjs {...props} />,
    "rest api": <TbApi {...props} />,
    graphql: <SiGraphql {...props} />,
    webhooks: <TbWebhook {...props} />,
    "openapi (swagger)": <TbFileDescription {...props} />,
    "oauth 2.0": <SiAuth0 {...props} />,
    "openid connect": <FaKey {...props} />,
    saml: <TbShieldLock {...props} />,
    "apple pay": <PaymentBrandLogo file="applepay.png" name="Apple Pay" />,
    "google pay": <PaymentBrandLogo file="googlepay.png" name="Google Pay" />,
    docker: <SiDocker {...props} />,
    salesforce: <ErpBrandLogo file="salesforce.svg" name="Salesforce" />,
    hubspot: <ErpBrandLogo file="hubspot.svg" name="HubSpot" />,
    "microsoft dynamics 365": <ErpBrandLogo file="dynamics365.svg" name="Microsoft Dynamics 365" />,
    sap: <ErpBrandLogo file="sap.svg" name="SAP" />,
    oracle: <ErpBrandLogo file="oracle.svg" name="Oracle" />,
    "zoho crm": <ErpBrandLogo file="zoho.svg" name="Zoho CRM" />,
    postman: <SiPostman {...props} />,
    strapi: <SiStrapi {...props} />,
    sanity: <SiSanity {...props} />,
    storyblok: <TbPuzzle {...props} />,
    "rest apis": <TbApi {...props} />,
    "third-party api integrations": <TbNetwork {...props} />,
    "unit testing": <TbTestPipe {...props} />,
    "integration testing": <TbTestPipe {...props} />,
    "end-to-end (e2e) testing": <TbTestPipe {...props} />,
    "performance testing": <TbSpeedboat {...props} />,
    "accessibility testing": <TbAccessible {...props} />,
    flutter: <SiFlutter {...props} />,
    "react native": <TbBrandReactNative {...props} />,
    dart: <SiDart {...props} />,
    websockets: <TbNetwork {...props} />,
    "biometric authentication": <FaFingerprint {...props} />,
    "in-app purchases": <TbShoppingCart {...props} />,
    "google maps": <SiGooglemaps {...props} />,
    mapbox: <SiMapbox {...props} />,
    "gps & geolocation services": <TbCurrentLocation {...props} />,
    "firebase cloud messaging (fcm)": <SiFirebase {...props} />,
    "push notifications": <FaBell {...props} />,
    "firebase analytics": <SiFirebase {...props} />,
    "google analytics": <SiGoogleanalytics {...props} />,
    "device compatibility testing": <TbDeviceMobile {...props} />,
    "email services": <TbApi {...props} />,
    "sms services": <FaBell {...props} />,
    "payment gateway integrations": <TbCreditCard {...props} />,
    "automated testing": <TbTestPipe {...props} />,
    dhl: <SiDhl {...props} />,
    fedex: <SiFedex {...props} />,
    ups: <SiUps {...props} />,
    aramex: <FaTruck {...props} />,
    shipstation: <TbPackage {...props} />,
    easypost: <TbPackage {...props} />,
    "local payment gateways": <TbCreditCard {...props} />,
    "buy now, pay later (bnpl) integrations": <TbCreditCard {...props} />,
    sadad: <PaymentBrandLogo file="sadad.png" name="SADAD" />,
    dibsy: <PaymentBrandLogo file="dibsy.jpg" name="Dibsy" />,
    fatora: <PaymentBrandLogo file="fatora.png" name="Fatora" />,
    qpay: <PaymentBrandLogo file="qpay.png" name="QPay" />,
    "tap payments": <PaymentBrandLogo file="tap.png" name="Tap Payments" />,
    paytabs: <PaymentBrandLogo file="paytabs.png" name="PayTabs" />,
    myfatoorah: <PaymentBrandLogo file="myfatoorah.png" name="MyFatoorah" />,
    hyperpay: <PaymentBrandLogo file="hyperpay.png" name="HyperPay" />,
    moyasar: <PaymentBrandLogo file="moyasar.png" name="Moyasar" />,
    telr: <PaymentBrandLogo file="telr.png" name="Telr" />,
    "network international": <PaymentBrandLogo file="network.png" name="Network International" />,
    "stc pay": <PaymentBrandLogo file="stcpay.png" name="STC Pay" />,
    mada: <PaymentBrandLogo file="mada.png" name="Mada" />,
    knet: <PaymentBrandLogo file="knet.png" name="KNET" />,
    benefit: <PaymentBrandLogo file="benefit.png" name="BENEFIT" />,
    omannet: <PaymentBrandLogo file="omannet.svg" name="OmanNet" />,
    fawry: <PaymentBrandLogo file="fawry.png" name="Fawry" />,
    tabby: <PaymentBrandLogo file="tabby.png" name="Tabby" />,
    tamara: <PaymentBrandLogo file="tamara.png" name="Tamara" />,
    noqoody: <PaymentBrandLogo file="noqoody.png" name="Noqoody" />,
    skipcash: <PaymentBrandLogo file="skipcash.svg" name="SkipCash" />,
  };

  return map[key] ?? <TbCode {...props} />;
}

/** Soft brand tint for icon well backgrounds */
export function techIconTint(name) {
  const key = name.toLowerCase();
  const colors = {
    wordpress: "#21759b",
    "wordpress multisite": "#21759b",
    "gutenberg / block editor": "#3858e9",
    "wp-cli": "#21759b",
    bedrock: "#777bb4",
    "roots sage": "#2075a1",
    "advanced custom fields (acf)": "#00d3ae",
    "custom post types & taxonomies": "#c8f04a",
    "custom php themes": "#777bb4",
    "block theme / fse": "#3858e9",
    elementor: "#92003b",
    divi: "#ff4200",
    "gutenberg custom blocks": "#3858e9",
    "timber / twig": "#78c043",
    "generatepress / kadence": "#1e72bd",
    "woocommerce hpos": "#96588a",
    "woocommerce subscriptions": "#96588a",
    "apple pay / google pay": "#ffffff",
    "html5 / css3": "#e34f26",
    "javascript / typescript": "#3178c6",
    "faust.js": "#0073aa",
    "sass / scss": "#cc6699",
    "php 8.x": "#777bb4",
    composer: "#885630",
    "wordpress rest api": "#21759b",
    wpgraphql: "#e10098",
    mariadb: "#c0765a",
    "redis object cache": "#dc382d",
    memcached: "#2b2b2b",
    "query monitor": "#c8f04a",
    "wp engine": "#0ec763",
    kinsta: "#5333ed",
    cloudways: "#2c3c8c",
    "litespeed / openlitespeed": "#6b3fa0",
    "runcloud / gridpane": "#19b4f2",
    "wp rocket": "#f56640",
    "litespeed cache": "#6b3fa0",
    "cloudflare apo": "#f38020",
    "yoast seo": "#a4286a",
    "rank math": "#ff308a",
    "new relic / apm": "#008c99",
    wordfence: "#c81e1e",
    sucuri: "#00a5e3",
    "cloudflare waf": "#f38020",
    "ssl / tls": "#003a70",
    "2fa / least privilege": "#c8f04a",
    "fail2ban / ssh hardening": "#ef4444",
    "local wp / laravel valet": "#2935cc",
    "git / github": "#ffffff",
    "github actions": "#2088ff",
    "deployhq / buddy": "#1cbf73",
    "phpunit / playwright": "#c8f04a",
    drupal: "#0678be",
    "craft cms": "#e5422b",
    "adobe experience manager (aem)": "#eb1000",
    contentful: "#2478cc",
    webflow: "#4353ff",
    wix: "#0c6efe",
    squarespace: "#aaaaaa",
    woocommerce: "#96588a",
    shopify: "#96bf48",
    magento: "#f26322",
    opencart: "#23a8e0",
    html5: "#e34f26",
    css3: "#1572b6",
    javascript: "#f7df1e",
    typescript: "#3178c6",
    react: "#61dafb",
    "next.js": "#ffffff",
    astro: "#ff5d01",
    "vue.js": "#42b883",
    svelte: "#ff3e00",
    "tailwind css": "#06b6d4",
    bootstrap: "#7952b3",
    sass: "#cc6699",
    php: "#777bb4",
    laravel: "#ff2d20",
    "node.js": "#339933",
    python: "#3776ab",
    django: "#092e20",
    "core web vitals": "#4285f4",
    "google lighthouse": "#f4511e",
    "pagespeed insights": "#4285f4",
    gtmetrix: "#c8f04a",
    "cloudflare cdn": "#f38020",
    "technical seo": "#c8f04a",
    "schema markup": "#c8f04a",
    "image optimization": "#c8f04a",
    "lazy loading": "#c8f04a",
    "cdn integration": "#c8f04a",
    vercel: "#ffffff",
    netlify: "#00c7b7",
    cloudflare: "#f38020",
    cpanel: "#ff6c2c",
    plesk: "#52bbea",
    aws: "#ff9900",
    azure: "#0078d4",
    digitalocean: "#0080ff",
    git: "#f05032",
    github: "#ffffff",
    gitlab: "#fc6d26",
    "ci/cd pipelines": "#c8f04a",
    "ssl certificates": "#003a70",
    "web application firewalls (waf)": "#c8f04a",
    "malware scanning": "#ef4444",
    "security hardening": "#c8f04a",
    "automated backups": "#c8f04a",
    "express.js": "#ffffff",
    nestjs: "#e0234e",
    postgresql: "#4169e1",
    mysql: "#4479a1",
    mongodb: "#47a248",
    "microsoft sql server": "#0078d4",
    firebase: "#ffca28",
    oauth: "#eb5424",
    jwt: "#ffffff",
    "single sign-on (sso)": "#c8f04a",
    "multi-factor authentication (mfa)": "#c8f04a",
    "role-based access control (rbac)": "#c8f04a",
    stripe: "#635bff",
    paypal: "#003087",
    paddle: "#ffdd2f",
    "lemon squeezy": "#ffc233",
    web3: "#f16822",
    "rest api": "#c8f04a",
    graphql: "#e10098",
    webhooks: "#c8f04a",
    "openapi (swagger)": "#85ea2d",
    "oauth 2.0": "#eb5424",
    "openid connect": "#c8f04a",
    saml: "#c8f04a",
    "apple pay": "#ffffff",
    "google pay": "#4285f4",
    docker: "#2496ed",
    salesforce: "#00a1e0",
    hubspot: "#ff7a59",
    "microsoft dynamics 365": "#0B53CE",
    sap: "#0faaff",
    oracle: "#C74634",
    "zoho crm": "#e42527",
    postman: "#ff6c37",
    strapi: "#4945ff",
    sanity: "#f03e2f",
    storyblok: "#09b3af",
    "rest apis": "#c8f04a",
    "third-party api integrations": "#c8f04a",
    "unit testing": "#c8f04a",
    "integration testing": "#c8f04a",
    "end-to-end (e2e) testing": "#c8f04a",
    "performance testing": "#c8f04a",
    "accessibility testing": "#c8f04a",
    flutter: "#02569b",
    "react native": "#61dafb",
    dart: "#0175c2",
    websockets: "#c8f04a",
    "biometric authentication": "#c8f04a",
    "in-app purchases": "#c8f04a",
    "google maps": "#4285f4",
    mapbox: "#4264fb",
    "gps & geolocation services": "#c8f04a",
    "firebase cloud messaging (fcm)": "#ffca28",
    "push notifications": "#c8f04a",
    "firebase analytics": "#ffca28",
    "google analytics": "#f9ab00",
    "device compatibility testing": "#c8f04a",
    "email services": "#c8f04a",
    "sms services": "#c8f04a",
    "payment gateway integrations": "#c8f04a",
    "automated testing": "#c8f04a",
    dhl: "#ffcc00",
    fedex: "#4d148c",
    ups: "#351c15",
    aramex: "#e30613",
    shipstation: "#3cba54",
    easypost: "#c8f04a",
    "local payment gateways": "#c8f04a",
    "buy now, pay later (bnpl) integrations": "#c8f04a",
    sadad: "#8b1538",
    dibsy: "#0ea5a4",
    fatora: "#2563eb",
    qpay: "#7c3aed",
    "tap payments": "#00a3e0",
    paytabs: "#1d4ed8",
    myfatoorah: "#16a34a",
    hyperpay: "#dc2626",
    moyasar: "#0f766e",
    telr: "#ea580c",
    "network international": "#1e3a8a",
    "stc pay": "#4b0082",
    mada: "#009639",
    knet: "#c8102e",
    benefit: "#e11d48",
    omannet: "#0ea5e9",
    fawry: "#f59e0b",
    tabby: "#3b82f6",
    tamara: "#7c3aed",
    noqoody: "#0f172a",
    skipcash: "#22c55e",
  };
  return colors[key] ?? "#c8f04a";
}

/** Readable icon color on dark wells (yellow JS etc. stay dark-friendly) */
export function techIconColor(name) {
  const key = name.toLowerCase();
  if (key === "javascript") return "#f7df1e";
  if (
    key === "next.js" ||
    key === "vercel" ||
    key === "squarespace" ||
    key === "github" ||
    key === "git / github" ||
    key === "express.js" ||
    key === "jwt" ||
    key === "apple pay" ||
    key === "apple pay / google pay" ||
    key === "memcached"
  ) {
    return "#ffffff";
  }
  return techIconTint(name);
}
