"use client";

import {
  SiWordpress,
  SiDrupal,
  SiCraftcms,
  SiContentful,
  SiWebflow,
  SiWix,
  SiSquarespace,
  SiHtml5,
  SiCss,
  SiJavascript,
  SiTypescript,
  SiReact,
  SiNextdotjs,
  SiAstro,
  SiVuedotjs,
  SiSvelte,
  SiTailwindcss,
  SiBootstrap,
  SiSass,
  SiPhp,
  SiNodedotjs,
  SiPython,
  SiPagespeedinsights,
  SiVercel,
  SiNetlify,
  SiCloudflare,
  SiCpanel,
  SiWoocommerce,
  SiShopify,
  SiLaravel,
  SiDjango,
  SiDigitalocean,
  SiGit,
  SiGithub,
  SiGitlab,
  SiLetsencrypt,
  SiExpress,
  SiNestjs,
  SiPostgresql,
  SiMysql,
  SiMongodb,
  SiFirebase,
  SiAuth0,
  SiJsonwebtokens,
  SiStripe,
  SiPaypal,
  SiGraphql,
  SiDocker,
  SiHubspot,
  SiPostman,
  SiStrapi,
  SiSanity,
  SiFlutter,
  SiDart,
  SiMapbox,
  SiGooglemaps,
  SiGoogleanalytics,
} from "react-icons/si";
import {
  FaAws,
  FaMicrosoft,
  FaShieldAlt,
  FaKey,
  FaUserLock,
  FaUsersCog,
  FaApple,
  FaGoogle,
  FaSalesforce,
  FaFingerprint,
  FaBell,
} from "react-icons/fa";
import {
  TbBrandAdobe,
  TbCode,
  TbSeo,
  TbSchema,
  TbPhoto,
  TbLoader,
  TbNetwork,
  TbBrandOpenSource,
  TbServer,
  TbShieldLock,
  TbBug,
  TbDatabase,
  TbRocket,
  TbSpeedboat,
  TbShoppingCart,
  TbCreditCard,
  TbApi,
  TbWebhook,
  TbFileDescription,
  TbBuilding,
  TbTestPipe,
  TbAccessible,
  TbPuzzle,
  TbBrandReactNative,
  TbCurrentLocation,
  TbDeviceMobile,
} from "react-icons/tb";

const SIZE = 22;

/**
 * Brand / concept icons for tech stack tiles.
 */
export default function TechBrandIcon({ name, color = "#c8f04a" }) {
  const props = { size: SIZE, color, "aria-hidden": true };
  const key = name.toLowerCase();

  const map = {
    wordpress: <SiWordpress {...props} />,
    drupal: <SiDrupal {...props} />,
    "craft cms": <SiCraftcms {...props} />,
    "adobe experience manager (aem)": <TbBrandAdobe {...props} />,
    contentful: <SiContentful {...props} />,
    webflow: <SiWebflow {...props} />,
    wix: <SiWix {...props} />,
    squarespace: <SiSquarespace {...props} />,
    woocommerce: <SiWoocommerce {...props} />,
    shopify: <SiShopify {...props} />,
    magento: <TbShoppingCart {...props} />,
    opencart: <TbBrandOpenSource {...props} />,
    html5: <SiHtml5 {...props} />,
    css3: <SiCss {...props} />,
    javascript: <SiJavascript {...props} />,
    typescript: <SiTypescript {...props} />,
    react: <SiReact {...props} />,
    "next.js": <SiNextdotjs {...props} />,
    astro: <SiAstro {...props} />,
    "vue.js": <SiVuedotjs {...props} />,
    svelte: <SiSvelte {...props} />,
    "tailwind css": <SiTailwindcss {...props} />,
    bootstrap: <SiBootstrap {...props} />,
    sass: <SiSass {...props} />,
    php: <SiPhp {...props} />,
    laravel: <SiLaravel {...props} />,
    "node.js": <SiNodedotjs {...props} />,
    python: <SiPython {...props} />,
    django: <SiDjango {...props} />,
    "core web vitals": <SiPagespeedinsights {...props} />,
    "google lighthouse": <TbSpeedboat {...props} />,
    "pagespeed insights": <SiPagespeedinsights {...props} />,
    gtmetrix: <TbRocket {...props} />,
    "cloudflare cdn": <SiCloudflare {...props} />,
    "technical seo": <TbSeo {...props} />,
    "schema markup": <TbSchema {...props} />,
    "image optimization": <TbPhoto {...props} />,
    "lazy loading": <TbLoader {...props} />,
    "cdn integration": <TbNetwork {...props} />,
    vercel: <SiVercel {...props} />,
    netlify: <SiNetlify {...props} />,
    cloudflare: <SiCloudflare {...props} />,
    cpanel: <SiCpanel {...props} />,
    plesk: <TbServer {...props} />,
    aws: <FaAws {...props} />,
    azure: <FaMicrosoft {...props} />,
    digitalocean: <SiDigitalocean {...props} />,
    git: <SiGit {...props} />,
    github: <SiGithub {...props} />,
    gitlab: <SiGitlab {...props} />,
    "ci/cd pipelines": <TbRocket {...props} />,
    "ssl certificates": <SiLetsencrypt {...props} />,
    "web application firewalls (waf)": <FaShieldAlt {...props} />,
    "malware scanning": <TbBug {...props} />,
    "security hardening": <TbShieldLock {...props} />,
    "automated backups": <TbDatabase {...props} />,
    "express.js": <SiExpress {...props} />,
    nestjs: <SiNestjs {...props} />,
    postgresql: <SiPostgresql {...props} />,
    mysql: <SiMysql {...props} />,
    mongodb: <SiMongodb {...props} />,
    "microsoft sql server": <FaMicrosoft {...props} />,
    firebase: <SiFirebase {...props} />,
    oauth: <SiAuth0 {...props} />,
    jwt: <SiJsonwebtokens {...props} />,
    "single sign-on (sso)": <FaKey {...props} />,
    "multi-factor authentication (mfa)": <FaUserLock {...props} />,
    "role-based access control (rbac)": <FaUsersCog {...props} />,
    stripe: <SiStripe {...props} />,
    paypal: <SiPaypal {...props} />,
    paddle: <TbCreditCard {...props} />,
    "lemon squeezy": <TbShoppingCart {...props} />,
    "rest api": <TbApi {...props} />,
    graphql: <SiGraphql {...props} />,
    webhooks: <TbWebhook {...props} />,
    "openapi (swagger)": <TbFileDescription {...props} />,
    "oauth 2.0": <SiAuth0 {...props} />,
    "openid connect": <FaKey {...props} />,
    saml: <TbShieldLock {...props} />,
    "apple pay": <FaApple {...props} />,
    "google pay": <FaGoogle {...props} />,
    docker: <SiDocker {...props} />,
    salesforce: <FaSalesforce {...props} />,
    hubspot: <SiHubspot {...props} />,
    "microsoft dynamics 365": <FaMicrosoft {...props} />,
    sap: <TbBuilding {...props} />,
    oracle: <TbDatabase {...props} />,
    "zoho crm": <TbBuilding {...props} />,
    postman: <SiPostman {...props} />,
    strapi: <SiStrapi {...props} />,
    sanity: <SiSanity {...props} />,
    storyblok: <TbPuzzle {...props} />,
    "rest apis": <TbApi {...props} />,
    "third-party api integrations": <TbNetwork {...props} />,
    "unit testing": <TbTestPipe {...props} />,
    "integration testing": <TbTestPipe {...props} />,
    "end-to-end (e2e) testing": <TbTestPipe {...props} />,
    "performance testing": <TbSpeedboat {...props} />,
    "accessibility testing": <TbAccessible {...props} />,
    flutter: <SiFlutter {...props} />,
    "react native": <TbBrandReactNative {...props} />,
    dart: <SiDart {...props} />,
    websockets: <TbNetwork {...props} />,
    "biometric authentication": <FaFingerprint {...props} />,
    "in-app purchases": <TbShoppingCart {...props} />,
    "google maps": <SiGooglemaps {...props} />,
    mapbox: <SiMapbox {...props} />,
    "gps & geolocation services": <TbCurrentLocation {...props} />,
    "firebase cloud messaging (fcm)": <SiFirebase {...props} />,
    "push notifications": <FaBell {...props} />,
    "firebase analytics": <SiFirebase {...props} />,
    "google analytics": <SiGoogleanalytics {...props} />,
    "device compatibility testing": <TbDeviceMobile {...props} />,
  };

  return map[key] ?? <TbCode {...props} />;
}

/** Soft brand tint for icon well backgrounds */
export function techIconTint(name) {
  const key = name.toLowerCase();
  const colors = {
    wordpress: "#21759b",
    drupal: "#0678be",
    "craft cms": "#e5422b",
    "adobe experience manager (aem)": "#eb1000",
    contentful: "#2478cc",
    webflow: "#4353ff",
    wix: "#0c6efe",
    squarespace: "#aaaaaa",
    woocommerce: "#96588a",
    shopify: "#96bf48",
    magento: "#f26322",
    opencart: "#23a8e0",
    html5: "#e34f26",
    css3: "#1572b6",
    javascript: "#f7df1e",
    typescript: "#3178c6",
    react: "#61dafb",
    "next.js": "#ffffff",
    astro: "#ff5d01",
    "vue.js": "#42b883",
    svelte: "#ff3e00",
    "tailwind css": "#06b6d4",
    bootstrap: "#7952b3",
    sass: "#cc6699",
    php: "#777bb4",
    laravel: "#ff2d20",
    "node.js": "#339933",
    python: "#3776ab",
    django: "#092e20",
    "core web vitals": "#4285f4",
    "google lighthouse": "#f4511e",
    "pagespeed insights": "#4285f4",
    gtmetrix: "#c8f04a",
    "cloudflare cdn": "#f38020",
    "technical seo": "#c8f04a",
    "schema markup": "#c8f04a",
    "image optimization": "#c8f04a",
    "lazy loading": "#c8f04a",
    "cdn integration": "#c8f04a",
    vercel: "#ffffff",
    netlify: "#00c7b7",
    cloudflare: "#f38020",
    cpanel: "#ff6c2c",
    plesk: "#52bbea",
    aws: "#ff9900",
    azure: "#0078d4",
    digitalocean: "#0080ff",
    git: "#f05032",
    github: "#ffffff",
    gitlab: "#fc6d26",
    "ci/cd pipelines": "#c8f04a",
    "ssl certificates": "#003a70",
    "web application firewalls (waf)": "#c8f04a",
    "malware scanning": "#ef4444",
    "security hardening": "#c8f04a",
    "automated backups": "#c8f04a",
    "express.js": "#ffffff",
    nestjs: "#e0234e",
    postgresql: "#4169e1",
    mysql: "#4479a1",
    mongodb: "#47a248",
    "microsoft sql server": "#0078d4",
    firebase: "#ffca28",
    oauth: "#eb5424",
    jwt: "#ffffff",
    "single sign-on (sso)": "#c8f04a",
    "multi-factor authentication (mfa)": "#c8f04a",
    "role-based access control (rbac)": "#c8f04a",
    stripe: "#635bff",
    paypal: "#003087",
    paddle: "#ffdd2f",
    "lemon squeezy": "#ffc233",
    "rest api": "#c8f04a",
    graphql: "#e10098",
    webhooks: "#c8f04a",
    "openapi (swagger)": "#85ea2d",
    "oauth 2.0": "#eb5424",
    "openid connect": "#c8f04a",
    saml: "#c8f04a",
    "apple pay": "#ffffff",
    "google pay": "#4285f4",
    docker: "#2496ed",
    salesforce: "#00a1e0",
    hubspot: "#ff7a59",
    "microsoft dynamics 365": "#0078d4",
    sap: "#0faaff",
    oracle: "#f80000",
    "zoho crm": "#e42527",
    postman: "#ff6c37",
    strapi: "#4945ff",
    sanity: "#f03e2f",
    storyblok: "#09b3af",
    "rest apis": "#c8f04a",
    "third-party api integrations": "#c8f04a",
    "unit testing": "#c8f04a",
    "integration testing": "#c8f04a",
    "end-to-end (e2e) testing": "#c8f04a",
    "performance testing": "#c8f04a",
    "accessibility testing": "#c8f04a",
    flutter: "#02569b",
    "react native": "#61dafb",
    dart: "#0175c2",
    websockets: "#c8f04a",
    "biometric authentication": "#c8f04a",
    "in-app purchases": "#c8f04a",
    "google maps": "#4285f4",
    mapbox: "#4264fb",
    "gps & geolocation services": "#c8f04a",
    "firebase cloud messaging (fcm)": "#ffca28",
    "push notifications": "#c8f04a",
    "firebase analytics": "#ffca28",
    "google analytics": "#f9ab00",
    "device compatibility testing": "#c8f04a",
  };
  return colors[key] ?? "#c8f04a";
}

/** Readable icon color on dark wells (yellow JS etc. stay dark-friendly) */
export function techIconColor(name) {
  const key = name.toLowerCase();
  if (key === "javascript") return "#f7df1e";
  if (
    key === "next.js" ||
    key === "vercel" ||
    key === "squarespace" ||
    key === "github" ||
    key === "express.js" ||
    key === "jwt" ||
    key === "apple pay"
  ) {
    return "#ffffff";
  }
  return techIconTint(name);
}
